"""match immobilized motorcycles spreadsheet

Revision ID: 90a6bbff7325
Revises: e60e74ecd8c9
Create Date: 2026-07-28 12:01:09.087066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a6bbff7325'
down_revision = 'e60e74ecd8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immobilized_motorcycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immobilized_motorcycles', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('responsible')

    # ### end Alembic commands ###
