"""add immobilized motorcycles

Revision ID: e60e74ecd8c9
Revises: 702358d63da6
Create Date: 2026-07-28 11:46:25.932763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60e74ecd8c9'
down_revision = '702358d63da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immobilized_motorcycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=160), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('chassis', sa.String(length=40), nullable=False),
    sa.Column('service_order', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('immobilized_motorcycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_immobilized_motorcycles_plate'), ['plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_immobilized_motorcycles_service_order'), ['service_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immobilized_motorcycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_immobilized_motorcycles_service_order'))
        batch_op.drop_index(batch_op.f('ix_immobilized_motorcycles_plate'))

    op.drop_table('immobilized_motorcycles')
    # ### end Alembic commands ###
